/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideToolbox: typeof import('./src/components/AsideToolbox.vue')['default']
    Comp: typeof import('./src/components/loading/UseSpin/Comp.vue')['default']
    Danmaku: typeof import('./src/components/icons/Danmaku.vue')['default']
    LoadingProvider: typeof import('./src/components/LoadingProvider.vue')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    NavigationMenu: typeof import('./src/components/NavigationMenu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NCountdown: typeof import('naive-ui')['NCountdown']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NowLoading: typeof import('./src/components/loading/NowLoading/index.vue')['default']
    NowLoadingFade: typeof import('./src/components/loading/NowLoading/NowLoadingFade.vue')['default']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    Onmyodama: typeof import('./src/components/icons/Onmyodama.vue')['default']
    OnmyodamaSpin: typeof import('./src/components/OnmyodamaSpin.vue')['default']
    ResourcesUsed: typeof import('./src/components/ResourcesUsed.vue')['default']
    Revolver: typeof import('./src/components/Revolver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sakura: typeof import('./src/components/icons/Sakura.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
